<?php

namespace Benji07\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Update the tags for a post from tags string
     *
     * @param Post $post post
     */
    public function updateTags(Post $post)
    {
        $string = $post->getTagsString();
        $post->getTags()->clear();

        $tags = explode(',', $string);

        foreach ($tags as $tag) {
            $tag = trim($tag);

            if ('' === $tag) {
                continue;
            }

            $t = $this->getTagRepository()->findOneBy(array('name' => $tag));

            if (null === $t) {
                $t = new Tag();
                $t->setName($tag);

                $this->getEntityManager()->persist($t);
            }

            $post->getTags()->add($t);
        }
    }

    /**
     * Get the tag repository
     *
     * @return EntityRepository
     */
    protected function getTagRepository()
    {
        return $this->getEntityManager()->getRepository('Benji07BlogBundle:Tag');
    }
}