<?php

namespace Benji07\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Get Published post query
     *
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getPublishedQuery()
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->where('p.status = :status')
            ->orderBy('p.publishedAt', 'DESC')

            ->setParameter('status', Post::STATUS_PUBLISHED);

        return $qb;
    }

    /**
     * Get Published post for a tag query
     *
     * @param Tag $tag tag
     *
     * @return Doctrine\ORM\QueryBuilder
     */
    public function getPublishedQueryForTag(Tag $tag)
    {
        $qb = $this->getPublishedQuery();

        $qb
            ->leftJoin('p.tags', 't')
            ->andWhere('t.id = :tag')

            ->setParameter('tag', $tag->getId());

        return $qb;
    }
}
