Benji07MainBundle:
    resource: "@Benji07MainBundle/Controller/"
    type:     annotation
    prefix:   /

Benji07BlogBundle:
    resource: "@Benji07BlogBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin